### ISSUE TITLE
tried to create a button but got and unknown error on ubuntu and macOS

### ISSUE THREAD

**Issue by carlhung** [pmacro/Suit#6]
private func createButton() -> Button {
    let size = view.bounds.size
    let rect = CGRect(origin: CGPoint(x: size.width - 40, y: size.height / 2), size: CGSize(width: 20, height: 20))
    let button = Button.init(frame: rect)
    button.draw(rect: rect)
    return button
}

view.add(subview: createButton())

on macOS:
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
Illegal instruction: 4

on linux:
'X11' /media/carlhung/USB_DISK/suitTestApp/.build/checkouts/X11: warning: system packages are deprecated; use system library targets instead
'GLib' glib.pc: warning: couldn't find pc file
'FreeType' libfreetype.pc: warning: couldn't find pc file
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
Current stack trace:
0    libswiftCore.so                    0x00007f680701f920 _swift_stdlib_reportFatalError + 69
1    libswiftCore.so                    0x00007f6806f2da06 <unavailable> + 3279366
2    libswiftCore.so                    0x00007f6806f2dd85 <unavailable> + 3280261
3    libswiftCore.so                    0x00007f6806d55810 _fatalErrorMessage(_:_:file:line:flags:) + 19
4    suitTestApp                        0x00005563965b6515 <unavailable> + 1131797
5    suitTestApp                        0x00005563964e51f9 <unavailable> + 274937
6    suitTestApp                        0x00005563965c14bb <unavailable> + 1176763
7    suitTestApp                        0x00005563965c1189 <unavailable> + 1175945
8    suitTestApp                        0x00005563965bead2 <unavailable> + 1166034
9    suitTestApp                        0x00005563964dc6e7 <unavailable> + 239335
10   suitTestApp                        0x0000556396529290 <unavailable> + 553616
11   suitTestApp                        0x0000556396528c98 <unavailable> + 552088
12   suitTestApp                        0x0000556396528773 <unavailable> + 550771
13   suitTestApp                        0x00005563964dc15c <unavailable> + 237916
14   suitTestApp                        0x00005563965c16d8 <unavailable> + 1177304
15   libc.so.6                          0x00007f6803d94ab0 __libc_start_main + 231
16   suitTestApp                        0x00005563964cfdfa <unavailable> + 187898
Illegal instruction (core dumped)

**Comment by pmacro** [comment]
You can't directly call the draw(rect:) method.  It gets called automatically by the system.  Removing that should resolve the crash.

Note that the init(frame: CGRect) initialiser will most likely be removed.  To layout a button (or any other view), please use the layout properties (see View+Layout.swift).  

For example, to set the size of a button you could do something like this:

button.width = 50%
button.height = 20~

Numbers suffixed with % are a percentage value, and ones suffixed with ~ are a constant.

To position views, there are also layout properties, but generally you configure those on the parent in order to specify how that parent's children are laid out.  Fortunately there is lots of documentation on how to layout views, since Suit uses Yoga for this:

https://yogalayout.com

The online tool they have is very useful for figuring out layouts, too.
